basePath: /
host: localhost:9999
info:
  contact: {}
  description: A matchmaking service API in Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Match-Event Backend API
  version: "1.0"
paths: {}
swagger: "2.0"
