basePath: /
definitions:
  models.Category:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.Event:
    properties:
      age_limit:
        type: integer
      capacity:
        type: integer
      categories:
        description: relational fields
        items:
          type: string
        type: array
      created_at:
        type: string
      description:
        type: string
      dress_code:
        type: string
      end_time:
        type: string
      id:
        type: string
      location:
        type: string
      name:
        type: string
      organizer:
        description: non-mandatory fields
        type: string
      participants:
        items:
          type: string
        type: array
      price:
        type: number
      start_time:
        type: string
      total_likes:
        type: integer
      updated_at:
        type: string
    type: object
  models.Level:
    enum:
    - country
    - state
    - city
    type: string
    x-enum-varnames:
    - Country
    - State
    - City
  models.Location:
    properties:
      created_at:
        type: string
      id:
        type: string
      level:
        $ref: '#/definitions/models.Level'
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.Review:
    properties:
      comment:
        type: string
      created_at:
        type: string
      event_id:
        type: string
      id:
        type: string
      rating:
        type: integer
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      joined_event:
        items:
          type: string
        type: array
      updated_at:
        type: string
      username:
        type: string
    type: object
  payload.CreateCategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  payload.CreateEventRequest:
    properties:
      age_limit:
        type: integer
      capacity:
        type: integer
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      dress_code:
        type: string
      end_time:
        type: string
      location:
        type: string
      name:
        type: string
      organizer:
        type: string
      price:
        type: number
      start_time:
        type: string
    required:
    - capacity
    - description
    - end_time
    - location
    - name
    - price
    - start_time
    type: object
  payload.CreateLocationRequest:
    properties:
      level:
        type: string
      name:
        type: string
    required:
    - level
    - name
    type: object
  payload.CreateResponse:
    properties:
      id:
        type: string
    type: object
  payload.CreateReviewRequest:
    properties:
      comment:
        type: string
      rating:
        type: integer
    required:
    - comment
    - rating
    type: object
  payload.GeneralResponse:
    properties:
      message:
        type: string
    type: object
  payload.GetCategoriesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Category'
        type: array
    type: object
  payload.GetEventsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Event'
        type: array
    type: object
  payload.GetLocationsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Location'
        type: array
    type: object
  payload.GetReviewsResponse:
    properties:
      average_rating:
        type: number
      data:
        items:
          $ref: '#/definitions/models.Review'
        type: array
    type: object
  payload.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  payload.LoginResponse:
    properties:
      token:
        type: string
    type: object
  payload.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  payload.UpdateCategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  payload.UpdateEventRequest:
    properties:
      age_limit:
        type: integer
      capacity:
        type: integer
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      dress_code:
        type: string
      end_time:
        type: string
      location:
        type: string
      name:
        type: string
      organizer:
        type: string
      price:
        type: number
      start_time:
        type: string
    required:
    - age_limit
    - capacity
    - categories
    - description
    - dress_code
    - end_time
    - location
    - name
    - organizer
    - price
    - start_time
    type: object
  payload.UpdateLocationRequest:
    properties:
      level:
        type: string
      name:
        type: string
    type: object
  payload.UpdateUserRequest:
    properties:
      username:
        type: string
    required:
    - username
    type: object
host: localhost:9999
info:
  contact: {}
  description: A matchmaking service API in Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Match-Event Backend API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.LoginResponse'
      summary: Login
      tags:
      - users
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Register a new user
      tags:
      - users
  /categories:
    get:
      consumes:
      - application/json
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetCategoriesResponse'
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Create Category
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/payload.CreateResponse'
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Delete a category
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Category
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Update a category
      tags:
      - categories
  /events:
    get:
      consumes:
      - application/json
      description: Get all events
      parameters:
      - description: Event name
        in: query
        name: name
        type: string
      - description: Event categories
        example: cat1,cat2
        in: query
        name: categories
        type: string
      - description: Event locations
        example: loc_a,loc_b
        in: query
        name: locations
        type: string
      - description: Event price start
        in: query
        name: price_start
        type: string
      - description: Event price end
        in: query
        name: price_end
        type: string
      - description: Event age limit
        in: query
        name: age_limit
        type: string
      - description: Event start time
        example: "2023-12-02T20:00:00.000Z"
        in: query
        name: start_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetEventsResponse'
      summary: Get all events
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Create an event
      parameters:
      - description: Event object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.CreateEventRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.CreateResponse'
      summary: Create an event
      tags:
      - events
  /events/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Delete an event
      tags:
      - events
    get:
      consumes:
      - application/json
      description: Get an event by ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
      summary: Get an event by ID
      tags:
      - events
    put:
      consumes:
      - application/json
      description: Update an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      - description: Event
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.UpdateEventRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Update an event
      tags:
      - events
  /events/{id}/join:
    post:
      consumes:
      - application/json
      description: Join an event
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Join an event
      tags:
      - events
  /events/popular:
    get:
      consumes:
      - application/json
      description: Get popular events
      parameters:
      - description: Top K
        in: query
        name: topK
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetEventsResponse'
      summary: Get popular events
      tags:
      - events
  /locations:
    get:
      consumes:
      - application/json
      description: Get locations
      parameters:
      - description: Location level
        in: query
        name: level
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetLocationsResponse'
      summary: Get locations
      tags:
      - locations
    post:
      consumes:
      - application/json
      description: Create a new location
      parameters:
      - description: Create Location
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.CreateLocationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/payload.CreateResponse'
      summary: Create a new location
      tags:
      - locations
  /locations/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a location
      parameters:
      - description: Location ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Delete a location
      tags:
      - locations
    put:
      consumes:
      - application/json
      description: Update a location
      parameters:
      - description: Location ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Location
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.UpdateLocationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Update a location
      tags:
      - locations
  /reviews/{event_id}:
    get:
      consumes:
      - application/json
      description: Get reviews of an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetReviewsResponse'
      summary: Get reviews of an event
      tags:
      - reviews
    post:
      consumes:
      - application/json
      description: Create a review
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Event ID
        in: path
        name: event_id
        required: true
        type: string
      - description: Review
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.CreateReviewRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/payload.CreateResponse'
      summary: Create a review
      tags:
      - reviews
  /reviews/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a review
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Review ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Delete a review
      tags:
      - reviews
  /users:
    get:
      consumes:
      - application/json
      description: Get user info
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get user info
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update a user
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/payload.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GeneralResponse'
      summary: Update a user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get user by id
      tags:
      - users
swagger: "2.0"
